spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_DATABASE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      jdbc-interceptors: com.amazonaws.xray.sql.mysql.TracingInterceptor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
